# Generated by Django 5.0.6 on 2024-06-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=28)),
                ('sroll', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('mark', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
